security:
    encoders:
        AppBundle/Entity/Utilisateur:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity: 
                class: AppBundle:Utilisateur
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            form_login:
                login_path: login
                check_path: 
            # Logout when the user changes
            logout_on_user_change: true
